blog: https://compositecode.blog/
description: This sentence has details about various things.
linkedin: https://www.linkedin.com/in/adron/
name: testing
twitch: https://twitch.tv/adronhall/
twitter: https://twitter.com/adron/
